### PR TITLE
Testing if there is enough free (2.5GB) space to install the node.

### PR DESCRIPTION
**Pull request by dwildcash**
Hi,

I think it could be a good idea to test if there is enough free space (ex (2.5GB) before installing the node. I also added few exit.

Iam new to Rise but it definitively a nice project!  I will try to get involved!

Regards.
dwildcash

### CODE REVIEW

**Review by vekexasia — CHANGES_REQUESTED** [review]
Good stuff @dwildcash  but could you please use the same spacing structure as the current code? "2 spaces and not tabs"

**Comment by dwildcash** [comment]
> Hi,
> 
> I think it could be a good idea to test if there is enough free space (ex (2.5GB) before installing the node. I also added few exit.
> 
> Iam new to Rise but it definitively a nice project! I will try to get involved!
> 
> Regards.
> dwildcash

Perfect let me correct the spacing...

**Review by dwildcash — COMMENTED** [review]
Please contact me if something is not ok.  Iam on telegram and slack under nickname dwildcash!

**Comment by vekexasia** [comment]
Thanks @dwildcash

**Pull request merged**
